apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: gdx-invt-perf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.20.0
        args: ["-f", "/mnt/locust/locustfile.py", "--worker", "--master-host", "locust-master"]
        volumeMounts:
        - name: locust-scripts
          mountPath: /mnt/locust
      volumes:
      - name: locust-scripts
        configMap:
          name: locust-scripts
